server:
  ssl:
    key-store: /usr/local/exam/ssl/tomcat.jks
    key-password: Qwer!@#$%

logging:
  path: /usr/log/exam/

spring:
  redis:
    host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/exam
    username: postgres
    password: 123456
